name: Update emojis

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a pull request
        required: false
        default: "false"
  schedule:
    # https://crontab.guru/#0_0_*/7_*_*
    - cron: "0 0 */7 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    if: github.repository_owner == 'luxass'
    steps:
      - uses: actions/checkout@v4.1.7

      - name: setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: setup node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20

      - name: install dependencies
        run: pnpm install

      - name: Save initial state of emoji URLs
        run: cp emoji-urls.json /tmp/emoji_before.json

      - name: run update:emojis script
        run: pnpm run update:emojis

      - name: process emoji changes
        id: emoji_changes
        run: |
          echo "content of /tmp/emoji_before.json:"
          cat /tmp/emoji_before.json
          echo "content of emoji-urls.json:"
          cat emoji-urls.json

          old=$(<"/tmp/emoji_before.json")
          new=$(<"emoji-urls.json")

          diff_output=$(jq -n --argjson a "$old" --argjson b "$new" '
            def diff(a; b):
              reduce (a | keys_unsorted[]) as $key
                ({}; . + { ($key): (if a[$key] == b[$key] then null elif (a[$key] | type) == "object" and (b[$key] | type) == "object" then diff(a[$key]; b[$key]) else { old: a[$key], new: b[$key] } end) });
            diff($a; $b)')

          echo "diff_output: $diff_output"

          cleaned_output=$(echo "$diff_output" | jq 'walk(if type == "object" then with_entries(select(.value != null)) else . end)')

          echo "cleaned_output: $cleaned_output"

      # - name: create pull request
      #   uses: peter-evans/create-pull-request@v6.1.0
      #   if: ${{ github.event.inputs.dry-run != 'true' && steps.emoji_changes.outputs.changes }}
      #   with:
      #     commit-message: "chore: updated emojis"
      #     title: "chore: updated github emojis"
      #     body: |
      #       I found some new changes in GitHub's list of emojis.

      #       Here's a summary of the changes:
      #       ${{ steps.emoji_changes.outputs.changes }}

      #       I don't know which emoji they changed or added, but I'm sure it's cool.
      #       If you want you can go take a look yourself.

      #       I will be waiting for your approval 👋.

      #       This is an automated PR to update the GitHub Emoji List.

      #       If you have any questions or suggestions, please open an issue.
      #     branch: update-emojis
      #     base: main
      #     committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
      #     author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
      #     reviewers: luxass

      # - name: Upload changes as artifact
      #   uses: actions/upload-artifact@v4.3.4
      #   if: steps.emoji_changes.outputs.changes
      #   with:
      #     name: emoji-changes
      #     path: ${{ steps.emoji_changes.outputs.changes }}
