name: Update emojis

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a pull request
        required: false
        default: "false"
  schedule:
    # https://crontab.guru/#0_0_*/7_*_*
    - cron: "0 0 */7 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    if: github.repository_owner == 'luxass'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v6.0.4

      - name: setup node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: lts/*

      - name: install dependencies
        run: pnpm install

      - name: save old emoji-urls file
        run: cp emoji-urls.json /tmp/old-emoji-urls.json

      - name: run update:emojis script
        run: pnpm run update:emojis

      - name: process emoji changes
        id: emoji_changes
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const { readFileSync } = require('fs');

            const oldEmojiUrls = JSON.parse(readFileSync('/tmp/old-emoji-urls.json', 'utf8'));
            const newEmojiUrls = JSON.parse(readFileSync('emoji-urls.json', 'utf8'));

            const changes = Object.keys(newEmojiUrls).reduce((acc, key) => {
              if (oldEmojiUrls[key] !== newEmojiUrls[key]) {
                acc[key] = newEmojiUrls[key]
              }
              return acc;
            }, {});

            let changesTable = '';
            for (let i = 0; i < Object.keys(changes).length; i += 3) {
              const key1 = Object.keys(changes)[i];
              const key2 = Object.keys(changes)[i + 1];
              const key3 = Object.keys(changes)[i + 2];
              changesTable += `| :${key1}: | ${key2 != null ? ':' + key2 + ':' : ''} | ${key3 != null ? ':' + key3 + ':' : ''} |\n`;
            }

            if (Object.keys(changes).length === 0) {
              core.setOutput('changes', 'false');
            } else {
              core.setOutput('changes', 'true');
              core.setOutput('changes-table', changesTable)
            }

      - name: create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        if: ${{ github.event.inputs.dry-run != 'true' && steps.emoji_changes.outputs.changes == 'true' }}
        with:
          commit-message: "chore: updated emojis"
          title: "chore: updated github emojis"
          body: |
            I found some new changes in GitHub's list of emojis.

            <details>
              <summary>Here you can see a list of the new emojis</summary>

              | Emoji | Emoji | Emoji |
              | ----- | ----- | ----- |
              ${{ steps.emoji_changes.outputs.changes-table }}
            </details>

            I don't know which emoji they changed or added, but I'm sure it's cool.
            If you want you can go take a look yourself.

            I will be waiting for your approval 👋.

            This is an automated PR to update the GitHub Emoji List.

            If you have any questions or suggestions, please open an issue.
          branch: update-emojis
          base: main
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          reviewers: luxass

      - name: upload new emojis as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: steps.emoji_changes.outputs.changes == 'true'
        with:
          name: new-github-emojis
          path: emoji-urls.json
