name: Update emojis

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Run the script without committing changes"
        required: false
        default: "false"
  schedule:
    # run first day of every month at 1:12
    - cron: "1 12 1 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Run update:list script
        run: bun run update:list

      - name: Check for changes
        id: check
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected"
            echo "CHANGES=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes detected"
            echo "CHANGES=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push changes 
        if: ${{ github.event.inputs.dry-run != 'true' && steps.check.outputs.CHANGES == 'true' }}
        run: |
          git config --local user.email "lucasnrgaard@gmail.com"
          git config --local user.name "luxass"

          git add README.md
          git add ./src/types.ts
          git add emojis.json

          git commit -m "chore(emojis): update emojis"
          git push
